apiVersion: v1
kind: Service
metadata:
  name: crypto-receiver-service
  namespace: crypto-system
  labels:
    app: crypto-app
    component: receiver
spec:
  type: ClusterIP
  selector:
    app: crypto-app
    component: receiver
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP

