//! P2P network behaviour: Kademlia DHT, GossipSub, Request-Response, Identify.
//!
//! This module composes all libp2p sub-protocols into a single
//! [`NodeBehaviour`] that the swarm drives. Each sub-protocol handles a
//! different aspect of the P2P communication:
//!
//! | Protocol         | Purpose                                      |
//! |------------------|----------------------------------------------|
//! | **Kademlia**     | Peer routing & DHT-based peer discovery      |
//! | **GossipSub**    | Transaction broadcast to all connected peers |
//! | **Req/Response**  | Direct peer-to-peer transfer confirmations   |
//! | **Identify**     | Peer capability & address advertisement      |
//! | **mDNS**         | Local network peer discovery (LAN fallback)  |

use anyhow::{Context, Result};
use libp2p::{
    gossipsub::{self, IdentTopic, MessageAuthenticity, ValidationMode},
    identify,
    kad::{self, store::MemoryStore, Config as KademliaConfig},
    mdns,
    request_response::{self, cbor, ProtocolSupport},
    swarm::NetworkBehaviour,
    PeerId, StreamProtocol,
};
use serde::{Deserialize, Serialize};
use std::time::Duration;
use tracing::info;

/// The GossipSub topic used for broadcasting new transactions.
pub const TX_TOPIC: &str = "/crypto-node/tx/1.0.0";

/// Protocol ID for direct request-response transfer confirmations.
pub const TRANSFER_PROTOCOL: &str = "/crypto-node/transfer/1.0.0";

// ── Request / Response messages ─────────────────────────────────────

/// A direct transfer request sent from sender → receiver.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransferRequest {
    /// RLP-encoded [`SignedTransaction`].
    pub tx_rlp: Vec<u8>,
}

/// A transfer response from receiver → sender.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransferResponse {
    /// Whether the receiver accepted the transaction.
    pub accepted: bool,
    /// Human-readable reason (empty on success).
    pub reason: String,
    /// The transaction hash for confirmation.
    pub tx_hash: String,
}

// ── Composed network behaviour ──────────────────────────────────────

/// Top-level network behaviour composing all sub-protocols.
///
/// The `#[derive(NetworkBehaviour)]` macro auto-generates the event
/// routing; each field handles its own protocol events.
#[derive(NetworkBehaviour)]
#[behaviour(to_swarm = "NodeEvent")]
pub struct NodeBehaviour {
    /// Kademlia DHT for peer discovery and routing.
    pub kademlia: kad::Behaviour<MemoryStore>,

    /// GossipSub for broadcasting transactions to all peers.
    pub gossipsub: gossipsub::Behaviour,

    /// Direct request-response for transfer confirmations.
    pub transfer: cbor::Behaviour<TransferRequest, TransferResponse>,

    /// Identify protocol for capability advertisement.
    pub identify: identify::Behaviour,

    /// mDNS for local peer discovery (LAN fallback).
    pub mdns: mdns::tokio::Behaviour,
}

/// Union event type generated by the `NetworkBehaviour` derive macro.
#[derive(Debug)]
pub enum NodeEvent {
    Kademlia(kad::Event),
    Gossipsub(gossipsub::Event),
    Transfer(request_response::Event<TransferRequest, TransferResponse>),
    Identify(identify::Event),
    Mdns(mdns::Event),
}

impl From<kad::Event> for NodeEvent {
    fn from(e: kad::Event) -> Self {
        Self::Kademlia(e)
    }
}
impl From<gossipsub::Event> for NodeEvent {
    fn from(e: gossipsub::Event) -> Self {
        Self::Gossipsub(e)
    }
}
impl From<request_response::Event<TransferRequest, TransferResponse>> for NodeEvent {
    fn from(e: request_response::Event<TransferRequest, TransferResponse>) -> Self {
        Self::Transfer(e)
    }
}
impl From<identify::Event> for NodeEvent {
    fn from(e: identify::Event) -> Self {
        Self::Identify(e)
    }
}
impl From<mdns::Event> for NodeEvent {
    fn from(e: mdns::Event) -> Self {
        Self::Mdns(e)
    }
}

// ── Builder ─────────────────────────────────────────────────────────

/// Construct a fully configured [`NodeBehaviour`].
///
/// # Arguments
/// * `local_key` - The node's Ed25519 identity keypair.
/// * `peer_id`   - The node's PeerId (derived from `local_key`).
pub fn build_behaviour(
    local_key: &libp2p::identity::Keypair,
    peer_id: PeerId,
) -> Result<NodeBehaviour> {
    // ── Kademlia ────────────────────────────────────────────────────
    let mut kad_config = KademliaConfig::new(StreamProtocol::new("/crypto-node/kad/1.0.0"));
    kad_config.set_query_timeout(Duration::from_secs(60));
    // Record TTL: 24 hours (prevents stale data accumulation)
    kad_config.set_record_ttl(Some(Duration::from_secs(86400)));
    // Provider TTL: 12 hours
    kad_config.set_provider_record_ttl(Some(Duration::from_secs(43200)));
    let store = MemoryStore::new(peer_id);
    let kademlia = kad::Behaviour::with_config(peer_id, store, kad_config);
    info!("Kademlia DHT initialised (query timeout: 60s)");

    // ── GossipSub ───────────────────────────────────────────────────
    let gossipsub_config = gossipsub::ConfigBuilder::default()
        .heartbeat_interval(Duration::from_secs(1))
        .validation_mode(ValidationMode::Strict)
        // Performance: limit message sizes to 64 KiB
        .max_transmit_size(65536)
        // Security: require message signing
        .build()
        .context("Failed to build GossipSub config")?;

    let mut gossipsub = gossipsub::Behaviour::new(
        MessageAuthenticity::Signed(local_key.clone()),
        gossipsub_config,
    )
    .map_err(|e| anyhow::anyhow!("Failed to create GossipSub behaviour: {e}"))?;

    // Subscribe to the transaction topic
    let topic = IdentTopic::new(TX_TOPIC);
    gossipsub
        .subscribe(&topic)
        .context("Failed to subscribe to tx topic")?;
    info!("GossipSub initialised, subscribed to {}", TX_TOPIC);

    // ── Request-Response (transfer confirmations) ───────────────────
    let transfer = cbor::Behaviour::new(
        [(
            StreamProtocol::new(TRANSFER_PROTOCOL),
            ProtocolSupport::Full,
        )],
        request_response::Config::default().with_request_timeout(Duration::from_secs(30)),
    );
    info!(
        "Request-Response protocol initialised: {}",
        TRANSFER_PROTOCOL
    );

    // ── Identify ────────────────────────────────────────────────────
    let identify = identify::Behaviour::new(
        identify::Config::new("/crypto-node/1.0.0".into(), local_key.public())
            .with_push_listen_addr_updates(true)
            .with_interval(Duration::from_secs(60)),
    );
    info!("Identify protocol initialised");

    // ── mDNS ────────────────────────────────────────────────────────
    let mdns = mdns::tokio::Behaviour::new(mdns::Config::default(), peer_id)
        .context("Failed to create mDNS behaviour")?;
    info!("mDNS initialised for local peer discovery");

    Ok(NodeBehaviour {
        kademlia,
        gossipsub,
        transfer,
        identify,
        mdns,
    })
}
